
import java.util.*;
import outils.FileStr;

/**
 * Module 633.1-Programmation / TP Série P10
 *
 * Fenêtre principale de l'application
 *
 * @author François Duvernay
 *
 */
public class FrmMain extends java.awt.Frame {

    private static final String PERSONNES = "Personnes.txt";
    private static final String CADEAUX = "Cadeaux.txt";
    private static final String CADEAUX_POUR = "Cadeaux pour ";
    private static final String SOMME = "Somme totale: ";
    private static final String DEL_MOTS = ";";
    private ArrayList listPersonnes = new ArrayList();
    private ArrayList listCadeaux = new ArrayList();

    /* Constructeur */
    public FrmMain() {
        initComponents();
        initListePers();
        lstPersonnes.select(0);
        initListeCadeau();
        initListeCadeauCourante((Personne)listPersonnes.get(lstPersonnes.getSelectedIndex()));
    } // Constructeur

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        java.awt.Label label1 = new java.awt.Label();
        lstPersonnes = new java.awt.List();
        lblCadeauxPour = new java.awt.Label();
        lstCadeauxCourante = new java.awt.List();
        lblSomme = new java.awt.Label();
        java.awt.Label label2 = new java.awt.Label();
        lstCadeaux = new java.awt.List();
        btnAjouter = new java.awt.Button();

        setTitle("Cadeaux de Noël");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        label1.setText("Personnes");

        lstPersonnes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstPersonnesItemStateChanged(evt);
            }
        });

        lblCadeauxPour.setText("Cadeaux pour XYZ");

        lblSomme.setText("Somme totale: 99.-");

        label2.setText("Cadeaux possibles");

        lstCadeaux.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstCadeauxItemStateChanged(evt);
            }
        });

        btnAjouter.setEnabled(false);
        btnAjouter.setLabel("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSomme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstCadeauxCourante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lstPersonnes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCadeauxPour, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAjouter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstCadeaux, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lstPersonnes, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCadeauxPour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lstCadeaux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstCadeauxCourante, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSomme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Fin de l'application */
  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      dispose();
  }//GEN-LAST:event_formWindowClosing

  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      System.exit(0);
  }//GEN-LAST:event_formWindowClosed

    private void lstPersonnesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstPersonnesItemStateChanged
        initListeCadeauCourante((Personne) listPersonnes.get(lstPersonnes.getSelectedIndex()));
    }//GEN-LAST:event_lstPersonnesItemStateChanged

    private void lstCadeauxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstCadeauxItemStateChanged
        if (lstCadeaux.getSelectedIndex() == -1) {
            btnAjouter.setEnabled(false);
        } else {
            Cadeau c = (Cadeau)listCadeaux.get(lstCadeaux.getSelectedIndex());
            Personne p = (Personne)listPersonnes.get(lstPersonnes.getSelectedIndex());
            ArrayList pList = p.getIdsCadeaux();
            boolean dedans = false;
            for (int i = 0; i < pList.size(); i++) {
                Cadeau actuel = new Cadeau(Integer.parseInt((String)pList.get(i)));
                if(c.equals(actuel)) {
                    dedans = true;
                }
            }
            if (dedans) {
                btnAjouter.setEnabled(false);
            }
            else{
                btnAjouter.setEnabled(true);
            }
        }
    }//GEN-LAST:event_lstCadeauxItemStateChanged

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        Personne p = (Personne) listPersonnes.get(lstPersonnes.getSelectedIndex());
        ArrayList idsCadeau = p.getIdsCadeaux();
        String index = String.valueOf(lstCadeaux.getSelectedIndex() + 1);
        idsCadeau.add(index);
        Personne remplace = new Personne(p.getNom(), idsCadeau);
        listPersonnes.set(lstPersonnes.getSelectedIndex(), remplace);
        initListeCadeauCourante(remplace);
        btnAjouter.setEnabled(false);
    }//GEN-LAST:event_btnAjouterActionPerformed

    /*Méthode pour transformer les tableaux en liste pour se faciliter la tâche.*/
    private ArrayList tabToList(String[] tab) {
        ArrayList liste = new ArrayList();
        for (int i = 0; i < tab.length; i++) {
            liste.add(tab[i]);
        }
        return liste;
    }//tabToList

    private void initListePers() {
        ArrayList liste = tabToList(FileStr.read(PERSONNES));
        for (int i = 0; i < liste.size(); i++) {
            ArrayList num = new ArrayList();
            StringTokenizer st = new StringTokenizer((String) liste.get(i), DEL_MOTS);
            String nom = st.nextToken();
            lstPersonnes.add(nom);
            while (st.hasMoreTokens()) {
                num.add(st.nextToken());
            }
            Personne p = new Personne(nom, num);
            listPersonnes.add(p);
        }
    }//initListePers

    private void initListeCadeau() {
        ArrayList liste = tabToList(FileStr.read(CADEAUX));
        for (int i = 0; i < liste.size(); i++) {
            StringTokenizer st = new StringTokenizer((String) liste.get(i), DEL_MOTS);
            int id = Integer.parseInt(st.nextToken());
            String libelle = st.nextToken();
            int prix = Integer.parseInt(st.nextToken());
            Cadeau c = new Cadeau(id, libelle, prix);
            lstCadeaux.add(c.toString());
            listCadeaux.add(c);
        }
    }//initListeCadeau

    private void initListeCadeauCourante(Personne p) {
        lstCadeauxCourante.clear();
        lblCadeauxPour.setText(CADEAUX_POUR + p.getNom());
        ArrayList idsCadeaux = p.getIdsCadeaux();
        int somme = 0;
        for (int i = 0; i < idsCadeaux.size(); i++) {
            int index = Integer.parseInt((String) idsCadeaux.get(i)) - 1;
            Cadeau c = (Cadeau) listCadeaux.get(index);
            lstCadeauxCourante.add(c.toString());
            somme += c.getPrix();
        }
        lblSomme.setText(SOMME + somme + ".-");
    }//initListeCadeauCourante

    /* Méthode principale */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAjouter;
    private java.awt.Label lblCadeauxPour;
    private java.awt.Label lblSomme;
    private java.awt.List lstCadeaux;
    private java.awt.List lstCadeauxCourante;
    private java.awt.List lstPersonnes;
    // End of variables declaration//GEN-END:variables

} // FrmMain
